# Generated by Django 3.0.6 on 2020-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200709_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
